### ISSUE TITLE
Exclude bot contributions

### ISSUE THREAD

**Issue by minrk** [executablebooks/github-activity#59]
### Description / Summary

I think it would be nice to be able to exclude bot contributions, such as pre-commit, dependabot, support, welcome, etc. Both from a contributor list and from the prs to include, possibly configured separately.

### Value / benefit

Limits noise in the contribution list to arguably 'actual' contributions. A section for dependency bumps automatically populated by pr author (well-known ones like pre-commit-bot, dependabot) in addition to current patterns of title/tag.

### Implementation details

Take an input list of usernames and/or look up metadata on the user accounts (I don't know if bots identify themselves?) and exclude those users from contributions in the report. Again, either from the contributor list or pr list or both.

### Tasks to complete

- [ ] option to specify accounts to exclude
- [ ] identify bots via metadata / patterns ?
- [ ] exclude accounts from output

**Comment by wolfv** [comment]
On another note I was just wondering if this tool could also accept the `Dependency` label that depend-a-bot applies (currently PRs are turning red with the label-enforcer: https://github.com/jupyterlab/maintainer-tools/issues/60)

**Comment by wolfv** [comment]
I am also seeing hte `codecov-commenter` in the contributors to the changelog:

```
[@codecov-commenter](https://github.com/search?q=repo%3Amamba-org%2Fquetz+involves%3Acodecov-commenter+updated%3A2022-03-14..2022-04-06&type=Issues)
```

**Comment by minrk** [comment]
closed by #65
